events {}

http {
  server {
    listen 80;

    location /nginx-health {
      add_header Content-Type text/plain;
      return 200 "nginx-proxy OK\n";
    }

    location / {
      proxy_pass http://host.docker.internal:5000;
    }
  }
}
