{
 "title": "lab-dom09",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"server_details_app_otel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second (by route)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"server_details_app_otel\"}[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "100 * (sum(rate(http_requests_total{job=\"server_details_app_otel\",status_code=~\"5..\"}[2m])) / sum(rate(http_requests_total{job=\"server_details_app_otel\"}[2m])))",
     "legendFormat": "error_rate %"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"server_details_app_otel\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"server_details_app_otel\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"server_details_app_otel\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Traces (latency > 300ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    { "minDuration": "300ms", "service": "server_details-app-otel" }
   ]
  },
  {
   "title": "Traces (Error - 500 responses)",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "query": "3bdb378fdb041fdc34e0cda817d61df0",
     "service": "server_details-app-otel",
     "tags": "http.response.status_code=500"
    }
   ]
  }
 ]
}