# --- DB credentials: generated by Terraform, stored in Secrets Manager, never committed ---

resource "random_password" "db_user_password" {
  length  = 20
  special = false
}

resource "random_password" "db_root_password" {
  length  = 20
  special = false
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name = var.secret_name
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id

  secret_string = jsonencode({
    MYSQL_DATABASE      = var.db_name
    MYSQL_USER          = var.db_user
    MYSQL_PASSWORD      = random_password.db_user_password.result
    MYSQL_ROOT_PASSWORD = random_password.db_root_password.result
  })
}

